"""Tests for the Azure OpenTofu module generator.

All tests are synchronous unit tests — no DB required.
"""

from __future__ import annotations

import shutil
from typing import Any
from unittest.mock import MagicMock

import pytest
from core.models import ProviderName


def _make_plan(
    target_provider: str = "azure",
    target_region: str = "eastus",
    vm_name: str = "web_01",
    disks: list[dict] | None = None,
    sizing_choices: list[dict] | None = None,
    assessment_findings: list[dict] | None = None,
) -> Any:
    """Build a minimal mock plan object for the generator."""
    plan = MagicMock()
    plan.target_provider = ProviderName.azure
    plan.target_region = target_region
    plan.plan_id = "test-plan-0001"
    plan.version = 1
    plan.name = "Test Migration Plan"
    plan.content_hash = "a" * 64

    resource = MagicMock()
    resource.id = "res-001"
    resource.name = vm_name
    resource.kind = "vm"
    resource.provider = "aws"
    resource.region = "us-east-1"

    plan.source_resources = [resource]
    plan.sizing_choices = sizing_choices or [{"sku": "Standard_D4s_v5", "provider": "azure"}]
    plan.assessment_findings = assessment_findings or []

    return plan


class TestAzureTofuGeneratorFiles:
    def test_generates_all_expected_files(self):
        from iac.generators.azure import AzureTofuGenerator
        gen = AzureTofuGenerator()
        module = gen.generate(_make_plan())

        expected_files = {
            "main.tf",
            "network.tf",
            "compute.tf",
            "variables.tf",
            "outputs.tf",
            "versions.tf",
        }
        assert expected_files == set(module.files.keys())

    def test_header_comment_in_each_file(self):
        from iac.generators.azure import AzureTofuGenerator
        gen = AzureTofuGenerator()
        module = gen.generate(_make_plan())

        for fname, content in module.files.items():
            assert "Generated by AETHER MIGRATE" in content, (
                f"Header comment missing in {fname}"
            )

    def test_versions_tf_has_correct_provider(self):
        from iac.generators.azure import AzureTofuGenerator
        gen = AzureTofuGenerator()
        module = gen.generate(_make_plan())

        versions = module.files["versions.tf"]
        assert "hashicorp/azurerm" in versions
        assert "~> 4.0" in versions
        assert ">= 1.6" in versions

    def test_compute_tf_uses_correct_vm_size(self):
        from iac.generators.azure import AzureTofuGenerator
        gen = AzureTofuGenerator()
        plan = _make_plan(sizing_choices=[{"sku": "Standard_D8s_v5"}])
        module = gen.generate(plan)

        compute = module.files["compute.tf"]
        assert "Standard_D8s_v5" in compute

    def test_compute_tf_default_vm_size_fallback(self):
        from iac.generators.azure import AzureTofuGenerator
        gen = AzureTofuGenerator()
        plan = _make_plan(sizing_choices=[])
        module = gen.generate(plan, vm_size="Standard_D4s_v5")

        compute = module.files["compute.tf"]
        assert "Standard_D4s_v5" in compute

    def test_network_nic_in_compute_tf(self):
        from iac.generators.azure import AzureTofuGenerator
        gen = AzureTofuGenerator()
        module = gen.generate(_make_plan())

        compute = module.files["compute.tf"]
        assert "azurerm_network_interface" in compute
        assert "azurerm_linux_virtual_machine" in compute

    def test_managed_disk_type_mapping_gp3(self):
        from iac.generators.azure import _map_disk_type
        assert _map_disk_type("gp3") == "Premium_LRS"

    def test_managed_disk_type_mapping_gp2(self):
        from iac.generators.azure import _map_disk_type
        assert _map_disk_type("gp2") == "Standard_LRS"

    def test_managed_disk_type_mapping_io1(self):
        from iac.generators.azure import _map_disk_type
        assert _map_disk_type("io1") == "UltraSSD_LRS"

    def test_managed_disk_type_mapping_io2(self):
        from iac.generators.azure import _map_disk_type
        assert _map_disk_type("io2") == "UltraSSD_LRS"

    def test_managed_disk_type_passthrough(self):
        from iac.generators.azure import _map_disk_type
        assert _map_disk_type("Premium_LRS") == "Premium_LRS"

    def test_nsg_in_network_tf(self):
        from iac.generators.azure import AzureTofuGenerator
        gen = AzureTofuGenerator()
        module = gen.generate(_make_plan())

        network = module.files["network.tf"]
        assert "azurerm_network_security_group" in network

    def test_sg_to_sg_rule_generates_todo_comment(self):
        from iac.generators.azure import AzureTofuGenerator
        gen = AzureTofuGenerator()
        findings_with_net002 = [{"rule_id": "NET-002", "evidence": {}, "title": "SG to SG"}]
        plan = _make_plan(assessment_findings=findings_with_net002)
        module = gen.generate(plan)

        network = module.files["network.tf"]
        assert "TODO" in network
        assert "SG-to-SG" in network or "NET-002" in network

    def test_variables_tf_has_required_variables(self):
        from iac.generators.azure import AzureTofuGenerator
        gen = AzureTofuGenerator()
        module = gen.generate(_make_plan())

        variables = module.files["variables.tf"]
        required = [
            "resource_group_name",
            "admin_username",
            "admin_ssh_key_path",
            "location",
        ]
        for var in required:
            assert f'variable "{var}"' in variables, f'Missing variable: {var}'

    def test_outputs_tf_has_resource_group_output(self):
        from iac.generators.azure import AzureTofuGenerator
        gen = AzureTofuGenerator()
        module = gen.generate(_make_plan())

        outputs = module.files["outputs.tf"]
        assert "resource_group_name" in outputs

    def test_module_provider_is_azure(self):
        from iac.generators.azure import AzureTofuGenerator
        gen = AzureTofuGenerator()
        module = gen.generate(_make_plan())

        assert module.provider == ProviderName.azure

    def test_module_region_matches_plan(self):
        from iac.generators.azure import AzureTofuGenerator
        gen = AzureTofuGenerator()
        module = gen.generate(_make_plan(target_region="westeurope"))

        assert module.region == "westeurope"


@pytest.mark.skipif(
    not shutil.which("tofu"),
    reason="tofu binary not installed — skipping live validation test",
)
class TestAzureTofuValidation:
    async def test_generated_module_validates(self):
        from iac.generators.azure import AzureTofuGenerator
        from iac.validator import validate_tofu_module

        gen = AzureTofuGenerator()
        module = gen.generate(_make_plan())
        result = await validate_tofu_module(module)

        assert result.valid, f"Validation errors: {result.errors}"

    async def test_validator_returns_result_when_tofu_missing(self):
        from iac.models import TofuModule
        from iac.validator import validate_tofu_module

        module = TofuModule(
            provider=ProviderName.azure,
            region="eastus",
            files={"main.tf": "# empty"},
            variables={},
            outputs={},
        )
        result = await validate_tofu_module(module, tofu_binary="tofu_does_not_exist_xyz")
        assert not result.valid
        assert any("not found" in e for e in result.errors)
