"""Plan export utilities for AETHER MIGRATE.

Provides three export formats:
  - JSON  (schema-versioned)
  - Markdown (suitable for PDF conversion)
  - ZIP   (OpenTofu module + README)
"""

from __future__ import annotations

import io
import json
import zipfile
from datetime import UTC, datetime
from typing import TYPE_CHECKING, Any

from planner.models import MigrationPlan

if TYPE_CHECKING:
    from iac.models import TofuModule


# ---------------------------------------------------------------------------
# JSON export
# ---------------------------------------------------------------------------


def export_json(plan: MigrationPlan) -> str:
    """Return a schema-versioned JSON string of the plan document."""
    doc = plan.model_dump(mode="json")
    doc["schema_version"] = "1.0"
    doc["exported_at"] = datetime.now(UTC).isoformat()
    return json.dumps(doc, indent=2, ensure_ascii=False)


# ---------------------------------------------------------------------------
# Markdown export
# ---------------------------------------------------------------------------


def _severity_label(severity: Any) -> str:
    mapping = {"blocker": "🔴 BLOCKER", "warning": "🟡 WARNING", "info": "ℹ️ INFO"}
    s = severity if isinstance(severity, str) else str(severity)
    return mapping.get(s, s.upper())


def export_markdown(plan: MigrationPlan) -> str:
    """Return a Markdown document suitable for PDF conversion."""
    lines: list[str] = []

    hash_short = (plan.content_hash or "")[:8] or "n/a"

    lines.append(f"# Migration Plan: {plan.name}")
    lines.append("")
    lines.append(f"**Version:** {plan.version}  ")
    lines.append("**Status:** draft  ")
    lines.append(f"**Plan ID:** `{plan.plan_id}`  ")
    lines.append(f"**Content Hash:** `{hash_short}...`  ")
    lines.append(f"**Target:** {plan.target_provider.value} / {plan.target_region}  ")
    lines.append(f"**Created:** {plan.created_at.isoformat()}  ")
    lines.append(f"**Catalog Version:** {plan.catalog_version}  ")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Source resources
    lines.append("## Source Resources")
    lines.append("")
    for res in plan.source_resources:
        name = res.name or res.id
        lines.append(f"- **{name}** (`{res.kind}`) — {res.provider}/{res.region}")
    lines.append("")

    # Prerequisites
    lines.append("## Prerequisites")
    lines.append("")
    for i, prereq in enumerate(plan.prerequisites, 1):
        lines.append(f"{i}. {prereq}")
    lines.append("")

    # Steps
    lines.append("## Migration Steps")
    lines.append("")
    for step in plan.steps:
        manual_tag = " *(manual)*" if step.is_manual else ""
        lines.append(f"### Step {step.step_number}: {step.title}{manual_tag}")
        lines.append("")
        lines.append(step.description)
        lines.append("")
        lines.append("| | |")
        lines.append("|---|---|")
        lines.append(f"| **Pre-check** | {step.pre_check} |")
        lines.append(f"| **Action** | {step.action} |")
        lines.append(f"| **Post-check** | {step.post_check} |")
        lines.append(f"| **Compensation** | {step.compensation} |")
        lines.append(f"| **Estimated duration** | {step.estimated_duration_minutes} min |")
        lines.append("")

    # Downtime estimate
    lines.append("## Downtime Estimate")
    lines.append("")
    lines.append(f"**Estimated downtime:** {plan.downtime_estimate_minutes} minutes")
    lines.append("")
    lines.append(f"**Basis:** {plan.downtime_basis}")
    lines.append("")

    # Findings summary
    findings = plan.assessment_findings
    if findings:
        lines.append("## Assessment Findings Summary")
        lines.append("")
        lines.append("| Severity | Rule | Title | Acknowledged |")
        lines.append("|---|---|---|---|")
        for f in findings:
            if isinstance(f, dict):
                sev = _severity_label(f.get("severity", ""))
                rule_id = f.get("rule_id", "")
                title = f.get("title", "")
                acked = "✓" if f.get("acknowledged") else "✗"
            else:
                sev = _severity_label(f.severity)
                rule_id = f.rule_id
                title = f.title
                acked = "✓" if f.acknowledged else "✗"
            lines.append(f"| {sev} | {rule_id} | {title} | {acked} |")
        lines.append("")

    # Rollback plan
    lines.append("## Rollback Plan")
    lines.append("")
    lines.append(plan.rollback_plan)
    lines.append("")

    # Assumptions
    lines.append("## Assumptions")
    lines.append("")
    for assumption in plan.assumptions:
        lines.append(f"- {assumption}")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "*This document was generated by AETHER MIGRATE v0.1.0. "
        "Review all steps carefully before execution.*"
    )

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# ZIP export (OpenTofu module + README)
# ---------------------------------------------------------------------------


def export_tofu_zip(plan: MigrationPlan, tofu_module: TofuModule) -> bytes:
    """Return a ZIP archive containing the OpenTofu module files and a README."""
    buf = io.BytesIO()

    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        module_dir = f"aether-migrate-plan-{plan.plan_id[:8]}"

        # Write README
        readme = _build_readme(plan, tofu_module)
        zf.writestr(f"{module_dir}/README.md", readme)

        # Write all module files
        for filename, content in tofu_module.files.items():
            zf.writestr(f"{module_dir}/{filename}", content)

    return buf.getvalue()


def _build_readme(plan: MigrationPlan, module: TofuModule) -> str:
    lines = [
        "# AETHER MIGRATE — OpenTofu Module",
        "",
        f"Plan: **{plan.name}** (v{plan.version})",
        "",
        f"Target: `{plan.target_provider.value}/{plan.target_region}`",
        "",
        f"Plan Hash: `{plan.content_hash or 'n/a'}`",
        "",
        "## Files",
        "",
    ]
    for fname in sorted(module.files.keys()):
        lines.append(f"- `{fname}`")

    lines += [
        "",
        "## Usage",
        "",
        "```bash",
        "# 1. Review and populate variables",
        "cp terraform.tfvars.example terraform.tfvars",
        "# Edit terraform.tfvars with your values",
        "",
        "# 2. Initialize",
        "tofu init",
        "",
        "# 3. Preview changes",
        "tofu plan",
        "",
        "# 4. Apply (requires approval)",
        "tofu apply",
        "```",
        "",
        "## Required Variables",
        "",
        "| Variable | Description |",
        "|---|---|",
    ]
    for name, var in module.variables.items():
        if var.default is None:
            lines.append(f"| `{name}` | {var.description} |")
    lines += [
        "",
        "---",
        "",
        "*Generated by AETHER MIGRATE v0.1.0 — review all resources before applying.*",
    ]
    return "\n".join(lines)
