"""Azure OpenTofu module generator for AETHER MIGRATE.

Generates a complete, syntactically valid OpenTofu module for the target
Azure landing zone from a MigrationPlan.

Generated files:
  main.tf       — provider block, resource group
  network.tf    — VNet, subnets, NSG(s) with security rules
  compute.tf    — VM(s) with managed disks and network interfaces
  variables.tf  — all variables with descriptions
  outputs.tf    — resource group name, VM IDs, NIC IDs
  versions.tf   — required_providers and required_version
"""

from __future__ import annotations

from typing import Any

from core.models import ProviderName

from iac.models import TofuModule, TofuVariable

_HEADER = "# Generated by AETHER MIGRATE v0.1.0 — review before applying\n"

# Mapping of AWS/generic disk type classes to Azure managed disk SKUs
_DISK_TYPE_MAP: dict[str, str] = {
    "gp3": "Premium_LRS",
    "gp2": "Standard_LRS",
    "io1": "UltraSSD_LRS",
    "io2": "UltraSSD_LRS",
    "st1": "Standard_LRS",
    "sc1": "Standard_LRS",
    "standard": "Standard_LRS",
    "premium": "Premium_LRS",
    "ultra": "UltraSSD_LRS",
    # Passthroughs
    "Premium_LRS": "Premium_LRS",
    "Standard_LRS": "Standard_LRS",
    "UltraSSD_LRS": "UltraSSD_LRS",
    "StandardSSD_LRS": "StandardSSD_LRS",
}


def _map_disk_type(type_class: str | None) -> str:
    if not type_class:
        return "Premium_LRS"
    return _DISK_TYPE_MAP.get(type_class, "Premium_LRS")


def _sanitize_name(name: str | None, fallback: str) -> str:
    """Return a valid Terraform resource name (alphanumeric + underscore)."""
    if not name:
        return fallback
    result = "".join(c if c.isalnum() or c == "_" else "_" for c in name)
    # Must start with letter or underscore
    if result and result[0].isdigit():
        result = "_" + result
    return result or fallback


class AzureTofuGenerator:
    """Generate a complete OpenTofu module for an Azure landing zone."""

    def generate(
        self,
        plan: Any,  # MigrationPlan — avoiding circular import
        vm_size: str = "Standard_D4s_v5",
    ) -> TofuModule:
        """Generate TofuModule from a MigrationPlan.

        Parameters
        ----------
        plan:
            A MigrationPlan domain object.
        vm_size:
            Azure VM SKU to use. Defaults to first like_for_like candidate
            if available, otherwise Standard_D4s_v5.
        """
        # Determine VM size from sizing choices
        effective_vm_size = vm_size
        for candidate in plan.sizing_choices:
            if isinstance(candidate, dict) and candidate.get("sku"):
                effective_vm_size = candidate["sku"]
                break

        # Collect source resource info
        source_resources = plan.source_resources
        findings = plan.assessment_findings

        # Check for SG-to-SG rules (NET-002 finding)
        has_sg_to_sg = any(
            (f.get("rule_id") == "NET-002" if isinstance(f, dict) else f.rule_id == "NET-002")
            for f in findings
        )

        files: dict[str, str] = {
            "versions.tf": self._versions_tf(),
            "variables.tf": self._variables_tf(plan),
            "main.tf": self._main_tf(plan),
            "network.tf": self._network_tf(plan, has_sg_to_sg),
            "compute.tf": self._compute_tf(plan, effective_vm_size),
            "outputs.tf": self._outputs_tf(plan),
        }

        variables = self._build_variables(plan)
        outputs = {
            "resource_group_name": "azurerm_resource_group.main.name",
        }
        for i, res in enumerate(source_resources):
            safe = _sanitize_name(res.get("name") if isinstance(res, dict) else res.name, f"vm_{i}")
            outputs[f"vm_{safe}_id"] = f"azurerm_linux_virtual_machine.{safe}.id"
            outputs[f"nic_{safe}_id"] = f"azurerm_network_interface.{safe}.id"

        return TofuModule(
            provider=ProviderName.azure,
            region=plan.target_region,
            files=files,
            variables=variables,
            outputs=outputs,
        )

    def _versions_tf(self) -> str:
        return (
            _HEADER
            + """
terraform {
  required_version = ">= 1.6"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
  }
}
"""
        )

    def _variables_tf(self, plan: Any) -> str:
        lines = [_HEADER, ""]
        lines.append('variable "resource_group_name" {')
        lines.append('  description = "Name of the Azure resource group to create."')
        lines.append('  type        = string')
        lines.append("}\n")

        lines.append('variable "location" {')
        lines.append('  description = "Azure region for all resources."')
        lines.append('  type        = string')
        lines.append(f'  default     = "{plan.target_region}"')
        lines.append("}\n")

        lines.append('variable "admin_username" {')
        lines.append('  description = "Administrator username for the VM(s)."')
        lines.append('  type        = string')
        lines.append("}\n")

        lines.append('variable "admin_ssh_key_path" {')
        lines.append('  description = "Path to SSH public key file."')
        lines.append('  type        = string')
        lines.append("}\n")

        lines.append('variable "vnet_address_space" {')
        lines.append('  description = "CIDR block for the VNet."')
        lines.append('  type        = string')
        lines.append('  default     = "10.0.0.0/16"')
        lines.append("}\n")

        lines.append('variable "subnet_address_prefix" {')
        lines.append('  description = "CIDR block for the default subnet."')
        lines.append('  type        = string')
        lines.append('  default     = "10.0.1.0/24"')
        lines.append("}\n")

        return "\n".join(lines)

    def _main_tf(self, plan: Any) -> str:
        region = plan.target_region
        return (
            _HEADER
            + f"""
provider "azurerm" {{
  features {{}}
}}

resource "azurerm_resource_group" "main" {{
  name     = var.resource_group_name
  location = "{region}"

  tags = {{
    managed_by    = "aether-migrate"
    target_region = "{region}"
  }}
}}
"""
        )

    def _network_tf(self, plan: Any, has_sg_to_sg: bool) -> str:
        lines = [_HEADER, ""]

        lines.append('resource "azurerm_virtual_network" "main" {')
        lines.append('  name                = "${var.resource_group_name}-vnet"')
        lines.append("  resource_group_name = azurerm_resource_group.main.name")
        lines.append("  location            = azurerm_resource_group.main.location")
        lines.append("  address_space       = [var.vnet_address_space]")
        lines.append("}\n")

        lines.append('resource "azurerm_subnet" "main" {')
        lines.append('  name                 = "${var.resource_group_name}-subnet"')
        lines.append("  resource_group_name  = azurerm_resource_group.main.name")
        lines.append("  virtual_network_name = azurerm_virtual_network.main.name")
        lines.append("  address_prefixes     = [var.subnet_address_prefix]")
        lines.append("}\n")

        lines.append('resource "azurerm_network_security_group" "main" {')
        lines.append('  name                = "${var.resource_group_name}-nsg"')
        lines.append("  resource_group_name = azurerm_resource_group.main.name")
        lines.append("  location            = azurerm_resource_group.main.location")
        lines.append("")

        # Generate security rules from assessment findings
        # Look for security group rules in the plan findings
        sg_rules = self._extract_sg_rules(plan)
        rule_priority = 100
        for idx, rule in enumerate(sg_rules):
            if rule.get("is_sg_to_sg"):
                lines.append(
                    f"  # TODO: SG-to-SG rule requires manual translation "
                    f"(rule {rule.get('rule_id', idx)})"
                )
                continue
            direction = rule.get("direction", "Inbound").capitalize()
            protocol_raw = rule.get("protocol", "Tcp")
            protocol = _translate_protocol(protocol_raw)
            port_range = rule.get("port_range", "*")
            peer_cidr = rule.get("peer_cidr", "*")
            priority = rule_priority + idx * 10

            lines.append("  security_rule {")
            lines.append(f'    name                       = "rule-{idx:03d}-{direction.lower()}"')
            lines.append(f'    priority                   = {priority}')
            lines.append(f'    direction                  = "{direction}"')
            lines.append('    access                     = "Allow"')
            lines.append(f'    protocol                   = "{protocol}"')
            lines.append('    source_port_range          = "*"')
            lines.append(f'    destination_port_range     = "{port_range}"')
            lines.append(f'    source_address_prefix      = "{peer_cidr}"')
            lines.append('    destination_address_prefix = "*"')
            lines.append("  }\n")

        if has_sg_to_sg:
            lines.append(
                "  # TODO: One or more SG-to-SG rules (NET-002) require manual translation"
            )

        # Always add SSH allow rule
        lines.append("  security_rule {")
        lines.append('    name                       = "allow-ssh"')
        lines.append(f"    priority                   = {rule_priority + len(sg_rules) * 10 + 100}")
        lines.append('    direction                  = "Inbound"')
        lines.append('    access                     = "Allow"')
        lines.append('    protocol                   = "Tcp"')
        lines.append('    source_port_range          = "*"')
        lines.append('    destination_port_range     = "22"')
        lines.append('    source_address_prefix      = "*"')
        lines.append('    destination_address_prefix = "*"')
        lines.append("  }\n")

        lines.append("}\n")

        lines.append('resource "azurerm_subnet_network_security_group_association" "main" {')
        lines.append("  subnet_id                 = azurerm_subnet.main.id")
        lines.append("  network_security_group_id = azurerm_network_security_group.main.id")
        lines.append("}\n")

        return "\n".join(lines)

    def _compute_tf(self, plan: Any, vm_size: str) -> str:
        lines = [_HEADER, ""]

        source_resources = plan.source_resources

        for i, res in enumerate(source_resources):
            res_name = res.get("name") if isinstance(res, dict) else res.name
            safe = _sanitize_name(res_name, f"vm_{i}")
            res_id = res.get("id") if isinstance(res, dict) else res.id

            # Collect disks for this VM from plan document context
            # (disk specs come from assessment_findings evidence or sizing_choices)
            disks = self._extract_disks_for_resource(plan, res_id)

            # Network interface
            lines.append(f'resource "azurerm_network_interface" "{safe}" {{')
            lines.append(f'  name                = "{safe}-nic"')
            lines.append("  resource_group_name = azurerm_resource_group.main.name")
            lines.append("  location            = azurerm_resource_group.main.location")
            lines.append("")
            lines.append("  ip_configuration {")
            lines.append(f'    name                          = "{safe}-ipconfig"')
            lines.append("    subnet_id                     = azurerm_subnet.main.id")
            lines.append('    private_ip_address_allocation = "Dynamic"')
            lines.append("  }")
            lines.append("}\n")

            # Managed disks
            for d_idx, disk in enumerate(disks):
                disk_type = _map_disk_type(disk.get("type_class"))
                size_gib = int(disk.get("size_gib") or 32)
                disk_res_name = f"{safe}_disk_{d_idx}"
                lines.append(f'resource "azurerm_managed_disk" "{disk_res_name}" {{')
                lines.append(f'  name                 = "{safe}-disk-{d_idx}"')
                lines.append("  resource_group_name  = azurerm_resource_group.main.name")
                lines.append("  location             = azurerm_resource_group.main.location")
                lines.append(f'  storage_account_type = "{disk_type}"')
                lines.append('  create_option        = "Empty"')
                lines.append(f"  disk_size_gb         = {size_gib}")
                lines.append("}\n")

            # VM
            lines.append(f'resource "azurerm_linux_virtual_machine" "{safe}" {{')
            lines.append(f'  name                = "{safe}"')
            lines.append("  resource_group_name = azurerm_resource_group.main.name")
            lines.append("  location            = azurerm_resource_group.main.location")
            lines.append(f'  size                = "{vm_size}"')
            lines.append("  admin_username      = var.admin_username")
            lines.append("")
            lines.append("  admin_ssh_key {")
            lines.append("    username   = var.admin_username")
            lines.append('    public_key = file(var.admin_ssh_key_path)')
            lines.append("  }")
            lines.append("")
            lines.append("  network_interface_ids = [")
            lines.append(f"    azurerm_network_interface.{safe}.id,")
            lines.append("  ]")
            lines.append("")
            lines.append("  os_disk {")
            lines.append('    caching              = "ReadWrite"')
            lines.append('    storage_account_type = "Premium_LRS"')
            lines.append("  }")
            lines.append("")
            lines.append("  source_image_reference {")
            lines.append('    publisher = "Canonical"')
            lines.append('    offer     = "0001-com-ubuntu-server-jammy"')
            lines.append('    sku       = "22_04-lts-gen2"')
            lines.append('    version   = "latest"')
            lines.append("  }")
            lines.append("")
            lines.append("  lifecycle {")
            lines.append("    prevent_destroy = false")
            lines.append("  }")
            lines.append("}\n")

            # Attach data disks
            for d_idx, disk in enumerate(disks):
                if not disk.get("boot", False):
                    disk_res_name = f"{safe}_disk_{d_idx}"
                    lines.append(
                        f'resource "azurerm_virtual_machine_data_disk_attachment" "{disk_res_name}" {{'
                    )
                    lines.append(
                        f"  managed_disk_id    = azurerm_managed_disk.{disk_res_name}.id"
                    )
                    lines.append(
                        f"  virtual_machine_id = azurerm_linux_virtual_machine.{safe}.id"
                    )
                    lines.append(f"  lun                = {d_idx}")
                    lines.append('  caching            = "ReadWrite"')
                    lines.append("}\n")

        return "\n".join(lines)

    def _outputs_tf(self, plan: Any) -> str:
        lines = [_HEADER, ""]

        lines.append('output "resource_group_name" {')
        lines.append('  description = "Name of the created resource group."')
        lines.append("  value       = azurerm_resource_group.main.name")
        lines.append("}\n")

        for i, res in enumerate(plan.source_resources):
            res_name = res.get("name") if isinstance(res, dict) else res.name
            safe = _sanitize_name(res_name, f"vm_{i}")

            lines.append(f'output "vm_{safe}_id" {{')
            lines.append(f'  description = "Resource ID of VM {res_name}."')
            lines.append(f"  value       = azurerm_linux_virtual_machine.{safe}.id")
            lines.append("}\n")

            lines.append(f'output "nic_{safe}_id" {{')
            lines.append(f'  description = "Resource ID of NIC for {res_name}."')
            lines.append(f"  value       = azurerm_network_interface.{safe}.id")
            lines.append("}\n")

        return "\n".join(lines)

    def _build_variables(self, plan: Any) -> dict[str, TofuVariable]:
        return {
            "resource_group_name": TofuVariable(
                description="Name of the Azure resource group to create.",
                type="string",
                default=None,
                sensitive=False,
            ),
            "location": TofuVariable(
                description="Azure region for all resources.",
                type="string",
                default=plan.target_region,
                sensitive=False,
            ),
            "admin_username": TofuVariable(
                description="Administrator username for the VM(s).",
                type="string",
                default=None,
                sensitive=False,
            ),
            "admin_ssh_key_path": TofuVariable(
                description="Path to SSH public key file.",
                type="string",
                default=None,
                sensitive=False,
            ),
            "vnet_address_space": TofuVariable(
                description="CIDR block for the VNet.",
                type="string",
                default="10.0.0.0/16",
                sensitive=False,
            ),
            "subnet_address_prefix": TofuVariable(
                description="CIDR block for the default subnet.",
                type="string",
                default="10.0.1.0/24",
                sensitive=False,
            ),
        }

    def _extract_sg_rules(self, plan: Any) -> list[dict]:
        """Extract security group rules from plan findings evidence."""
        rules: list[dict] = []
        for finding in plan.assessment_findings:
            evidence = finding.get("evidence", {}) if isinstance(finding, dict) else {}
            sg_rules = evidence.get("sg_rules", [])
            for rule in sg_rules:
                rules.append(rule)
        return rules

    def _extract_disks_for_resource(self, plan: Any, resource_id: str) -> list[dict]:
        """Extract disk specs for a specific resource from the plan document."""
        for finding in plan.assessment_findings:
            if isinstance(finding, dict):
                evidence = finding.get("evidence", {})
                if evidence.get("resource_id") == resource_id:
                    disks = evidence.get("disks", [])
                    if disks:
                        return disks
        # Default: single 32 GiB OS disk
        return [{"size_gib": 32, "type_class": "gp3", "boot": True}]


def _translate_protocol(protocol: str) -> str:
    """Translate protocol name to Azure NSG protocol format."""
    mapping = {
        "tcp": "Tcp",
        "udp": "Udp",
        "icmp": "Icmp",
        "-1": "*",
        "all": "*",
    }
    return mapping.get(protocol.lower(), "Tcp")
