"""Connection domain types shared between the API and connector workers.

Nothing in this module may carry secret material except ``*Secret`` models, which
exist only on the write path (API → OpenBao) and the read path inside connector
workers (OpenBao → SDK).
"""

from __future__ import annotations

import re
from datetime import datetime
from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, SecretStr, field_validator

from aether.core.enums import AuthMethod, CheckStatus, ConnectionStatus

AWS_ROLE_ARN_RE = re.compile(r"^arn:aws(-cn|-us-gov)?:iam::\d{12}:role/[\w+=,.@/-]{1,512}$")
AWS_REGION_RE = re.compile(r"^[a-z]{2}(-gov)?-[a-z]+-\d$")


def _validate_regions(v: list[str]) -> list[str]:
    for r in v:
        if not AWS_REGION_RE.match(r):
            raise ValueError(f"invalid AWS region: {r}")
    return sorted(set(v))


class AwsAssumeRoleConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    auth_method: Literal[AuthMethod.AWS_ASSUME_ROLE] = AuthMethod.AWS_ASSUME_ROLE
    role_arn: str
    # Generated by the platform (confused-deputy protection); never user-chosen.
    external_id: str | None = None
    regions: list[str] = Field(default_factory=list, description="Empty = all enabled regions")
    home_region: str = Field(
        default="us-east-1", pattern=AWS_REGION_RE.pattern, description="Region for control-plane calls"
    )

    @field_validator("role_arn")
    @classmethod
    def _role_arn(cls, v: str) -> str:
        if not AWS_ROLE_ARN_RE.match(v):
            raise ValueError("must be an IAM role ARN like arn:aws:iam::123456789012:role/AetherReadOnly")
        return v

    @field_validator("regions")
    @classmethod
    def _regions(cls, v: list[str]) -> list[str]:
        return _validate_regions(v)

    @property
    def account_id(self) -> str:
        return self.role_arn.split(":")[4]


class AwsAccessKeyConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    auth_method: Literal[AuthMethod.AWS_ACCESS_KEY] = AuthMethod.AWS_ACCESS_KEY
    regions: list[str] = Field(default_factory=list, description="Empty = all enabled regions")
    home_region: str = Field(
        default="us-east-1", pattern=AWS_REGION_RE.pattern, description="Region for control-plane calls"
    )

    @field_validator("regions")
    @classmethod
    def _regions(cls, v: list[str]) -> list[str]:
        return _validate_regions(v)


ConnectionConfig = Annotated[AwsAssumeRoleConfig | AwsAccessKeyConfig, Field(discriminator="auth_method")]


class AwsAccessKeySecret(BaseModel):
    model_config = ConfigDict(extra="forbid")

    access_key_id: SecretStr
    secret_access_key: SecretStr

    @field_validator("access_key_id")
    @classmethod
    def _akid(cls, v: SecretStr) -> SecretStr:
        if not re.fullmatch(r"AKIA[A-Z0-9]{16}", v.get_secret_value()):
            raise ValueError("must be a long-term IAM user access key id (AKIA…)")
        return v


class CheckResult(BaseModel):
    id: str
    status: CheckStatus
    message: str
    details: dict[str, object] = Field(default_factory=dict)


class ConnectionTestResult(BaseModel):
    status: ConnectionStatus
    identity: dict[str, str] = Field(default_factory=dict)
    checks: list[CheckResult] = Field(default_factory=list)
    cloud_calls: list[str] = Field(default_factory=list, description="service:operation:outcome")
    tested_at: datetime

    @staticmethod
    def overall(checks: list[CheckResult]) -> ConnectionStatus:
        if any(c.status == CheckStatus.FAIL for c in checks):
            return ConnectionStatus.ERROR
        if any(c.status == CheckStatus.WARN for c in checks):
            return ConnectionStatus.WARNING
        return ConnectionStatus.OK
